name: Perfil Status

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Baixar Imagens de Status
        run: |
          curl -o github-readme-stats.svg "https://vercel.app"
          curl -o github-readme-top-langs.svg "https://vercel.app"

      - name: Salvar no Repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add github-readme-stats.svg
          git commit -m "Update Stats" || echo "Sem mudancas"
          git push origin main
